name: CI/CD Pipeline for Voice-Over Application
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v0.8.0'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}   

    - name: Log in to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: us-central1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Generate Version Tag
      id: version
      run: |
        VERSION=$(echo "${GITHUB_SHA:0:7}-$(date +%Y%m%d%H%M%S)")
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: us-central1-docker.pkg.dev/walmart-retail-media/gcp-audio/gcp-audio:${{ env.VERSION }}

    - name: Debug Deploy Command
      run: |
        echo "Deploy Command: gcloud run deploy voice-over --image us-central1-docker.pkg.dev/walmart-retail-media/gcp-audio/gcp-audio:${{ env.VERSION }} --platform managed --region us-central1 --allow-unauthenticated"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy voice-over \
          --image us-central1-docker.pkg.dev/walmart-retail-media/gcp-audio/gcp-audio:${{ env.VERSION }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
